name: "Goral bug report"
description: You encountered a problem using Goral
labels: ["bug"]
assignees:
  - maksimryndin
body:
  - type: markdown
    attributes:
      value: |
        # Hi!

        Thank you for using Goral and taking time to file a bug report.
  - type: checkboxes
    attributes:
      label: Preliminary checks
      description: Please make sure that you verify each checkbox and follow the instructions for them.
      options:
        - label: "This issue is a bug report. For a feature request or other question feel free to use a blank issue."
          required: true
        - label: "I've updated Goral to the latest version: https://github.com/maksimryndin/goral/releases and the bug still exists"
          required: true
        - label: "I've searched existing issues https://github.com/maksimryndin/goral/issues for the same bug and there is nothing similar"
          required: true
  - type: textarea
    attributes:
      label: Description
      description: Describe the issue that you're seeing (including a log message).
      placeholder: Be as precise as you can. Feel free to share screenshots, videos, or logs.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps to reproduce
      description: Clear steps describing how to reproduce the issue.
      value: |
        1.
        2.
        3.
        ...
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected result
      description: Describe what you expected to happen.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Actual result
      description: Describe what actually happened.
    validations:
      required: true
  - type: dropdown
    id: os
    validations:
      required: true
    attributes:
      label: What kind of operating system do you run Goral with?
      multiple: false
      options:
        - Linux
        - Mac OS
        - Windows
        - Other (please specify in the description)
  - type: dropdown
    id: cpuarch
    validations:
      required: true
    attributes:
      label: What kind of CPU architecture do you run Goral with?
      multiple: false
      options:
        - aarch64
        - x86-64
        - Other (please specify in the description)
  - type: dropdown
    id: goral_version
    validations:
      required: true
    attributes:
      label: Which version of Goral do you run (`goral --version`)?
      multiple: false
      options:
        - 0.1.7
        - 0.1.6
        - 0.1.5
        - 0.1.4
        - 0.1.3
        - 0.1.2
        - 0.1.1
        - 0.1.0
